# Generated by Django 5.1 on 2024-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ori_name', models.TextField()),
                ('year', models.IntegerField()),
                ('poster', models.TextField()),
                ('genre', models.TextField()),
                ('creators', models.TextField()),
                ('director', models.TextField()),
                ('actors', models.TextField()),
                ('description', models.TextField()),
                ('rating_imdb', models.FloatField()),
                ('rating_kinopoisk', models.FloatField()),
            ],
        ),
    ]
