# Generated by Django 5.1 on 2024-09-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Фильм/сериал', 'verbose_name_plural': 'Фильмы/сериалы'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.TextField(verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='creators',
            field=models.TextField(verbose_name='Создатели'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.TextField(verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.TextField(verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ori_name',
            field=models.TextField(verbose_name='Название ориг.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.TextField(verbose_name='Файл-постер'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating_imdb',
            field=models.FloatField(verbose_name='IMDB'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating_kinopoisk',
            field=models.FloatField(verbose_name='Кинопоиск'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(verbose_name='Название файла-скриншота')),
                ('url', models.TextField(verbose_name='Полный URL для файла-скриншота')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.movies', verbose_name='ID фильма')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
    ]
