# Generated by Django 5.1 on 2024-09-01 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movies_options_alter_movies_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shots',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.movies', verbose_name='Фильм'),
        ),
    ]
